FROM nginx:1.21.6

RUN echo '<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title></head><body>Mi pagina de inicio personalizada en su 2da version</body></html>' > /usr/share/nginx/html/index.html